# Site settings
title: stefanzweifel.io
email: hello@stefanzweifel.io
description: "Stefan Zweifel is a fullstack developer based in Zurich."
baseurl: ""
url: "https://stefanzweifel.io"
timezone: Europe/Zurich
name: stefanzweifel.io


# Build settings
markdown: kramdown

permalink: posts/:title

# Collections!
collections:
    portfolio:
        output: true
        permalink: /portfolio/:path/

#Special Things
include:     ['.htaccess']
exclude:     ['_dev', 'node_modules', '_drafts', 'README.md', 'gulpfile.js', 'package.json', 'gulpconfig.json', 'gulpconfig.json.example', '_deploy.sh']


image_url: "http://stefanzweifel.io/img"


gems:
  - jekyll-sitemap