# Site settings
title: stefanzweifel.io
email: hello@stefanzweifel.io
description: "Stefan Zweifel is a fullstack developer based in Zurich."
baseurl: ""
url: "https://stefanzweifel.io"
timezone: Europe/Zurich
name: stefanzweifel.io
source: "./src"
destination: "./dist"

# Build settings
markdown: kramdown

permalink: posts/:title/

# Collections!
collections:
    portfolio:
        output: true
        permalink: /portfolio/:path/

image_url: "http://stefanzweifel.io/img"

exclude: [vendor]

gems:
  - jekyll-sitemap

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false